### ISSUE TITLE
Gelsight publishing frequency

### ISSUE THREAD

**Issue by fhogan** [mcubelab/rgrasp#26]
@mariabauza @OleguerCanal 

I figured out why the gelsight frequency was sometimes around 1hz and other times around 10hz. Here is the logic:

1. If we stream the gelsight images as raw type in RViz, then the recording rate (for raw_image) is low in terminal (around 1-3hz)

2. If we stream the gelsight images as compressed type in RViz, then the recording rate (for raw_image) is high in terminal (around 10-12hz)

3- If we dont stream gelsight in RViz,  then the recording rate (for raw_image) is high in terminal (around 13hz).

Conclusion: Displaying the gelsight images in RViz slows down publishing frequency. 

Other note: I think we should make an effort to save images as raw_image instead of compressed. Compressed is meant for video streaming. Also, Peter says saving as compressed (JPEG) is bad a idea.

**Comment by albertor** [comment]
This is interesting. Good catch!
I think in ARC we used to remove some of the visualizations from RViz, because it was slowing down the system.

13 Hz is better than 1Hz, but I would say that it might be still a bit on the short side. When we have time it would be great to track the information flow and see where is the bottleneck between camera-RasberryPI-ROS-PC-RViz.

**Comment by mariabauza** [comment]
Thanks Frank! We can talk more about it today, but good catch!
